# Generated by Django 4.0.6 on 2022-09-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_plant_fertilizers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='water_interval',
            field=models.IntegerField(help_text='Enter in days.'),
        ),
    ]
