# Generated by Django 4.0.6 on 2022-09-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('common_name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('care_difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], default='E', max_length=1)),
                ('light_requirement', models.CharField(choices=[('L', 'Low Light'), ('I', 'Bright Indirect'), ('D', 'Direct')], default='I', max_length=1)),
                ('water_interval', models.IntegerField()),
            ],
        ),
    ]
