# Generated by Django 4.0.6 on 2022-09-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_fertilizer_watering'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='fertilizers',
            field=models.ManyToManyField(to='main_app.fertilizer'),
        ),
    ]
