# Generated by Django 4.0.6 on 2022-09-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_plant_water_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer',
            name='nutrient_balance',
            field=models.CharField(help_text='Enter as XX:XX:XX or XX-XX-XX', max_length=8),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='rec_freq',
            field=models.CharField(help_text='Check packaging instructions', max_length=100),
        ),
    ]
