# Generated by Django 4.0.6 on 2022-09-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer',
            name='rec_freq',
            field=models.CharField(help_text='Check packaging instructions', max_length=100, verbose_name='Recommended Frequency'),
        ),
    ]
